export const en_US: Record<string, string> = {
  'ui.app-bar.toolbar.color-mode-switch.mode.dark': 'dark',
  'ui.app-bar.toolbar.color-mode-switch.mode.light': 'light',
  'ui.app-bar.toolbar.color-mode-switch.tooltip': 'Switch to {mode}',

  'ui.app-bar.widgets.workflow.button.export-to-file': 'Export to file',
  'ui.app-bar.widgets.workflow.button.import-from-file': 'Import from file',
  'ui.app-bar.widgets.workflow.button.queue-prompt': 'Queue prompt',
  'ui.app-bar.widgets.workflow.button.redo': 'Redo',
  'ui.app-bar.widgets.workflow.button.undo': 'Undo',
  'ui.app-bar.widgets.workflow.status-block.executed-prompts': 'Executed prompts',
  'ui.app-bar.widgets.workflow.status-block.remaining-queue': 'Remaining queue',

  'ui.node.context-menu.change-color': 'Change color',
  'ui.node.context-menu.change-color.item.reset-color': 'Reset color',
  'ui.node.context-menu.convert-input-to-widget': 'Convert to widget',
  'ui.node.context-menu.convert-input-to-widget.item': '<colored>{input}</colored>',
  'ui.node.context-menu.convert-widget-to-input': 'Convert to input',
  'ui.node.context-menu.convert-widget-to-input.item': '<colored>{widget}</colored>',
  'ui.node.context-menu.disconnect-all': 'Disconnect all',

  'ui.quick-actions.reset-all-colors.tooltip': 'Reset all colors',
  'ui.quick-actions.resize-to-snap-grip.tooltip': 'Resize to snap grid',
  'ui.quick-actions.select-all.tooltip': 'Select all',

  'ui.side-bar.general.code-theme': 'Code theme',
  'ui.side-bar.general.language': 'Language',
  'ui.side-bar.general.theme': 'Theme',
  'ui.side-bar.general.title': 'General',
  'ui.side-bar.workflow.background': 'Background',
  'ui.side-bar.workflow.edge-type': 'Edge type',
  'ui.side-bar.workflow.handle-type': 'Handle type',
  'ui.side-bar.workflow.snap-grid': 'Snap grid',
  'ui.side-bar.workflow.snap-to-grid': 'Snap to grid',
  'ui.side-bar.workflow.title': 'Workflow',
  'ui.side-bar.workspaces.title': 'Workspaces',
};
