name: Build and test artifact

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: master
        path: |
          dist
          index.html
